# Generated by Django 3.2.25 on 2025-02-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Band', 'Band')], default='Customer', max_length=20),
        ),
    ]
