# Generated by Django 3.2.25 on 2025-02-13 00:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.verification_image_upload_path),
        ),
    ]
