# Generated by Django 5.1.6 on 2025-02-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='phone_number',
        ),
    ]
