# Generated by Django 5.1.6 on 2025-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_band_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Pending'), (1, 'Verified')], default=0),
        ),
    ]
