# Generated by Django 5.1.6 on 2025-02-21 02:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bandmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_image_upload_path),
        ),
    ]
