# Generated by Django 5.1.6 on 2025-03-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
