# Generated by Django 5.1.4 on 2025-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_message_conversation_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('CUSTOMER', 'Customers Only'), ('BAND', 'Bands Only')], default='ALL', max_length=20),
        ),
    ]
