# Generated by Django 5.1.4 on 2025-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('CUSTOMER', 'Customers Only'), ('BAND', 'Bands Only'), ('SPECIFIC', 'Specific Users')], default='ALL', max_length=20),
        ),
    ]
